### ISSUE TITLE
Add Java 21

### ISSUE THREAD

**Issue by Feliks-WR** [codewars/runner#305] opened 2024-05-18 08:02 UTC
- Name: Java
- Version: 21
- Release Note/Changelog: https://www.oracle.com/java/technologies/javase/21-relnote-issues.html#NewFeature

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Madjosz** [comment] 2024-05-18 08:14
Duplicate of #273.

**Comment by hobovsky** [comment] 2024-05-18 08:48
Closing as duplicate.

**Closed by hobovsky** 2024-05-18 08:48 UTC
Labels: request/language-version
