### ISSUE TITLE
Add Node v14

### ISSUE THREAD

**Issue by XRFXLP** [codewars/runner#119] opened 2021-04-30 14:05 UTC
Please complete the following information:

- JavaScript
- Node v14
- Release Note/Changelog: https://nodejs.org/en/blog/release/v14.16.1

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment] 2021-05-05 01:14
We only add Node versions that reached "Active LTS" (production ready) status. See https://nodejs.org/en/about/releases/

Qualified customers don't need the bleeding edge, and installed packages may not be ready until the Node version is widely used in production.
Also, JavaScript setup for Codewars is a mess like any languages that was added in the early days, and we've been failing to keep up with the pace. I make any necessary breaking changes to the runner when adding a new language version, and I don't want to add v16 now and be stuck with it for many years. After updating existing kata to v12, I can add v14, then v16 can be added maybe later this year after it becomes Active LTS.

Once the JavaScript setup is in a better shape, we can update more easily and hopefully keep up with them (new version per year).

### Update Plan

#### From v8 to v10

Updating from Node v8 to v10 needs more work because of the test framework change similar to Ruby 3.0. And the authors are using the custom test framework in many unexpected ways. I honestly had forgotten about this until very recently, so it's my fault that this is still not done. I haven't posted the list because I'm still experimenting and running with the fixes between work.

The following updates were done with scripts so far (changes are verified by running the test):

- Remove `Test.` from `Test.describe` and `Test.it`
- If the test doesn't include any `describe` or `it`, wrap the assertions:
  ```javascript
  describe("Tests", () => {
    it("test", () => {
    // original tests
    });
  });
  ```
  (I should do this for Ruby later)
- Comment out myjinxin's useless test groups (`describe -> console.log("message")`)

Other issues that can be fixed with a simple script:

- Unary test callback. Apparently, some authors thinks `_ => {}` is the same as `() => {}`. 
  ```javascript
  describe("Tests", () => {
    it("test", _ => {
    });
  });
  ```
  This is incompatible with v10 because the test is considered asynchronous. Usually used like this:
  ```javascript
  describe("Tests", () => {
    it("test", (done) => {
      // ...
      doSomething(() => {
        done();
      });
    });
  });
  ```

Other issues that may require manual fixes:

- Invalid test structure:
  ```javascript
  describe("Tests", () => {
    Test.assertEqual(add(1, 1), 2);
  });
  ```
  I might revisit this script I was working on a few years ago to automate this. https://astexplorer.net/#/gist/f043782cdfa46b7a00683f44cf51638e/20bdb95e15f2a60ea87858a4c43a99c4bcfe235c

#### From v10 to v12

This should be easy to automate.

- If test contains assertions from `Test.`, prepend `const Test = require("@codewars/test-compat");`, or switch to `chai.assert`.

### Planned Changes

- Stop concatenating without breaking everything

**Comment by XRFXLP** [comment] 2021-06-03 00:37
An issue with updating node 8 to node 10 by the script was that for comparison of array, the tests were giving feedback as following:
```
expected [ Array(12) ] to deeply equal [ Array(12) ]
````
Making the kata undebuggable, but it seems that this can be fixed by setting `chai.config.thresold = 0` (although I am not sure why this works as documentation do not mention the functionality of this aspect )

**Comment by kazk** [comment] 2021-06-03 02:47
Oh, that's because Node 10 makes the old assertions available with https://github.com/codewars/javascript-test-compat like Node 12, but implicitly. That package is just a wrapper around Chai. I can set `chai.config.truncateThreshold = 0;` in that package to make the migration easier.

**Comment by kazk** [comment] 2021-06-04 01:06
Deployed the change, so it shouldn't be truncated anymore.

**Comment by metasean** [comment] 2021-07-02 15:50
@kazk - I have to admit, I'm a hair bit confused.

- XRFXLP originally posted this question on Apr 30th 2021 (i.e. 2021-04-30).

- On May 4th 2021, your initial response started off with:
  >We only add Node versions that reached "Active LTS" (production ready) status. See https://nodejs.org/en/about/releases/
- However, the Node release table on the linked page indicates that Node 14 became the "Active LTS" version on 2020-10-27, which was **_six months prior_** to XRFXLP's original post.

The rest of your responses all make sense _to a degree_, eg. "Qualified customers don't need the bleeding edge...", "JavaScript setup for Codewars is a mess like any languages that was added in the early days...", "...we've been failing to keep up with the pace...", etc.

However, that very first statement in your initial response where you're indicating that the reason Node 14 isn't supported is because the requested version wasn't the "Active LTS" version, seems more than a _bit off_.

I'd also like to note that:
- Node v10 is no longer considered a "LTS" version, which means that JS/Node katas that don't currently support v12 might not even work with what is considered perfectly acceptable code in any of the currently supported versions of Node. (Which is exactly how I ended up here, i.e. I couldn't use functionality that works in _all currently supported_ versions of node.)
- As a Red subscriber, while I'm confident that our income pales in comparison to "Qualified" customers, we're still customers —_right?_—  I'm sure that I'm not the only subscriber who would like to be able to complete and create katas using language features that are in _**any** of the currently supported versions of Node_.  

(I wish I could say that if the runner was still open source, I'd try to make the patch, but I doubt that I'd finish it on my short vacation. 😞   However, I am at least [_trying_ to fix one itty-bitty kata](https://github.com/codewars/codewars.com/discussions/2415).)

**Comment by kazk** [comment] 2021-07-02 20:07
@metasean 

> However, that very first statement in your initial response where you're indicating that the reason Node 14 isn't supported is because the requested version wasn't the "Active LTS" version, seems more than a bit off.

![image](https://user-images.githubusercontent.com/639336/124322767-e6174880-db34-11eb-92b1-f17bbd32b4a8.png)

The original request was for v16. I'm explaining why we're behind, what I've done so far, and what I'm planning to do. I've also made https://github.com/codewars/content-issues/wiki/List-of-JavaScript-Kata-to-Update since that comment.

> I wish I could say that if the runner was still open source, I'd try to make the patch,

You're misunderstanding me completely. Adding a new language version is the easiest part.

**Comment by metasean** [comment] 2021-07-02 21:30
@kazk 

>The original request was for v16, so I explained why we're not adding it.

That makes a whole lot more sense.  Thank you for explaining!

>I wish I could say that if the runner was still open source, I'd try to make the patch,

>Adding a new language version is the easiest part.

I totally understand that the problem is the way JavaScript is currently implemented in the overall system (with apparently a ton of tech debt from the early days).  My points were simply that I wish I had more time to help; but, even if I had the time, since the runner is no longer open sourced, I wouldn't be able to help.  All three of these (i.e. tech debt/implementation challenges, my lack of time to contribute, & the code base's lack of open sourceness) make me sad.

**Comment by kazk** [comment] 2021-07-02 22:40
No, you're still not understanding. Open sourcing the runner won't help at all because that's not where the problem is. The runner works like how it's [described](https://github.com/codewars/runner/blob/main/README.md#code). For JavaScript, it simply does the following:

1. preprocess (concatenate preloaded, solution and tests)
2. copy files into the container
3. call `mocha` with our custom reporter (https://github.com/codewars/mocha-reporter) in the container

The long term goal is to make JavaScript testing in Codewars to work just like how it does outside Codewars (get rid of the step 1). The runner **supports it already** because we do that at Qualified.

The problem is updating thousands of existing content that depends on the problematic implementation. Like I wrote in the wiki page, making codemod like https://astexplorer.net/#/gist/f043782cdfa46b7a00683f44cf51638e/20bdb95e15f2a60ea87858a4c43a99c4bcfe235c will be the most helpful.
Any other ideas to update them are appreciated as well.

Technically, there's nothing blocking to add v14. But JavaScript already has more versions than other languages: v8, v10, and v12. And I wanted to get rid of Node v8 first.

What do you need from v14?

**Comment by kazk** [comment] 2021-12-23 22:34
Added v14 because Qualified needed some updates. I think most kata with Node v12 enabled can be upgraded automatically.

**Closed by kazk** 2021-12-23 22:34 UTC
Labels: request/language-version, language/javascript

**Comment by farhan443** [comment] 2021-12-23 23:04
> Added v14 because Qualified needed some updates. I think most kata with Node v12 enabled can be upgraded automatically.

I think so. Assuming they're all using Mocha & Chai, not the old test framework. Although I've never yet to find one that does.

**Comment by kazk** [comment] 2021-12-23 23:05
Updated 1065 kata has Node v14 now.

**Comment by XRFXLP** [comment] 2021-12-24 08:40
> I can add v14, then v16 can be added maybe later this year after it becomes Active LTS.

By the way, v16 is in the active LTS state from October 26, 2021 ([source](https://nodejs.org/en/about/releases/)).

(Though keeping the latest version barely matters in the context of codewars)

**Comment by Chrono79** [comment] 2022-09-02 12:16
Any news about implementing Node v16? I would be useful to add support for replaceAll for example.

**Comment by kazk** [comment] 2022-09-07 05:26
@Chrono79 
Please open a new issue to discuss. I also need to look up how much we have left to upgrade the ancient versions.
