### ISSUE TITLE
exit() can be abused in the C runner

### ISSUE THREAD

**Issue by VojtechBrezina** [codewars/runner#321] opened 2024-11-03 09:17 UTC
**Describe the bug**

When using C, you can just call `exit(0)` and pass all tests. (The exact exit status doesn't seem to be important.)

I haven't tried to actually submit the solution, but testing and attempting works fine.

**To Reproduce**

Try solving any kata in C with something like this:
```c
void function_you_are_supposed_to_write(){
    exit(0);
}
```

**Expected behavior**

Not sure. But the runner should notice that all the tests haven't been run. Another alternative is to somehow disable `exit`, but that might not be possible in C.

**Screenshots**

![image](https://github.com/user-attachments/assets/0ce2f7ae-4774-4126-97e7-aa83f1a27ded)

**Comment by hobovsky** [comment] 2024-11-14 08:56
Please see #246 and discussions linked from there.

I am going to close this one as a duplicate of #246 and a `won't fix`.

**Closed as completed by hobovsky** 2024-11-14 08:56 UTC
