### ISSUE TITLE
Add Elixir v1.14

### ISSUE THREAD

**Issue by fireindark707** [codewars/runner#251] opened 2023-06-08 11:11 UTC
Please complete the following information:

- Name: Elixir
- Version: 1.14
- Release Note/Changelog: [release note](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)

The introduction of dbg/2, a macro similar to IO.inspect/2, but tailored for debugging, which can print the value of whatever you pass to it, the debugged code itself, and its location​[1](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)​.
Improved errors on binary construction and evaluation introduced by Erlang/OTP 25, making debugging easier​[1](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)​.
The introduction of stepped ranges in Elixir 1.12, which Elixir 1.14 starts to take advantage of with support for stepped ranges in a couple of functions like Enum.slice/2 and binary_slice/2 (and binary_slice/3) in the Kernel module​[1](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)​.
Changes to the convention for some of the standard-library structs. The Inspect implementation for those structs now returns a string with a valid Elixir expression that recreates the struct when evaluated, allowing the internals of structs like MapSet, Version.Requirement, and Date.Range to be hidden while keeping it as valid Elixir code​[1](https://elixir-lang.org/blog/2022/09/01/elixir-v1-14-0-released/)​.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by kazk** [comment] 2023-12-19 02:46
Elixir 1.15 will be added as requested by a Qualified's customer.
Closing as duplicate of #132.

**Closed by kazk** 2023-12-19 02:46 UTC
Labels: request/language-version
