### ISSUE TITLE
range-v3 integration issue with Igloo for C++ kata

### ISSUE THREAD

**Issue by omaf2021** [codewars/runner#266] opened 2023-10-24 12:14 UTC
**Describe the bug**
Attempts to `#include <range/v3/all.hpp>` or, more specifically, `<range/v3/views/split.hpp>` fail to compile despite range-v3 being a [supported library](https://docs.codewars.com/languages/cpp/#packages) for C++ kata. This is because range-v3's `split.hpp` and Igloo both seem to respectively define a macro `It` which clash. This means that `ranges::views::split` becomes unusable, and you can't do the convenient `#include <range/v3/all.hpp>`. This can be worked around by using `push_macro` and `pop_macro`, but that's obviously overkill.

**To Reproduce**
To reproduce, `#include <range/v3/all.hpp>` or `<range/v3/views/split.hpp>` in any C++ kata. [Link to kumite](https://www.codewars.com/kumite/6537b40094f1d2a066f182f1).

**Expected behavior**
The expected behavior would be for the program to compile successfully.

**Comment by hobovsky** [comment] 2023-10-24 14:37
Duplicate of #142

**Closed by hobovsky** 2023-10-24 14:37 UTC
