### ISSUE TITLE
Add Lean 4

### ISSUE THREAD

**Issue by JoaoFelipe3** [codewars/runner#276] opened 2023-12-19 12:56 UTC
- Name: Lean
- Version: 4
- Release Note/Changelog: The Lean community is transitioning towards Lean 4, so it's now time for Codewars to do the transition.

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Kacarott** [comment] 2023-12-19 13:06
Duplicate of #263

**Closed by Kacarott** 2023-12-19 13:06 UTC
Labels: request/language-version
