### ISSUE TITLE
Add C++ 20

### ISSUE THREAD

**Issue by Feliks-WR** [codewars/runner#304] opened 2024-05-18 08:01 UTC
- Name: C++
- Version: 20
- Release Note/Changelog: https://en.cppreference.com/w/cpp/20

---

:+1: reaction _might_ help to get this request prioritized.

**Comment by Madjosz** [comment] 2024-05-18 08:15
Duplicate of #113.

**Comment by hobovsky** [comment] 2024-05-18 08:46
Closing as duplicate.

**Closed by hobovsky** 2024-05-18 08:46 UTC
Labels: request/language-version
